Feat add flywaydb
VlaPol/url_cuter pull request #2
Opened 2023-06-27 16:39 UTC by VlaPol

2023-06-27 21:10 UTC, oleg-grigorijan requested changes

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +        SqlParameterSource parametr = new MapSqlParameterSource("sName", inputRecord.getShortName()).addValue("url", inputRecord.getUrl());
Если что, там можно обычный `Map.of(...)` передавать

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +        return result.equals(shortName);
Что-то намудрил. `!list.isEmpty()`, например

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +                .replace("[", "").replace("]", ""));
Что-то сильно намудрил.  Даже с этим методом можно было бы `list.get(0)`. Можно `jdbcTemplate.queryForObject(..., Integer.class)`.
Вообще это даже опасная реализация. toString у List не требует конкретной реализации. Тебе спокойно могут вернуть класс списка, у которого toString не с [ ] переопределён.

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +        }
Обычно это ошибка с точки зрения бизнеса, проверка которой выносится на уровень сервисов. Из репозиториев чаще Optional возвращают

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +    NamedParameterJdbcTemplate jdbcTemplate;
private final

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +    NamedParameterJdbcTemplate jdbcTemplate;
Лучше использовать родительский интерфейс

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +    }
Зачем создавать на месте jdbc template? Мы привязываемся к реализации, не использем singleton. Тем более Spring Boot создаёт этот бин за нас. Просто принимаем его в конструкторе

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/resources/db.migration/V1__initial_schema.sql
> +-- SELECT us.url, us.short_name
Закомментированный код не оставляем

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/entity/ConvertRecord.java
> +@NoArgsConstructor(force = true)
Для чего тут force?

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/entity/ConvertRecord.java
> +@Data
Вот не рекомендую использовать аннотации ломбока, пока не прочитаешь документацию к ним. `@Data` уже в себя включает `@Getter`, `@Setter`, `@ToString`, `@EqualsAndHashCode`, `@RequiredArgsConstructor`

2023-06-27 21:10 UTC, grigo-oleg commented on src/main/resources/db.migration/V1__initial_schema.sql
Для flyway по идее должны быть отдельные директории `db` и `migration`, а не одна `db.migration`

2023-06-27 21:13 UTC, oleg-grigorijan commented
Давай создадим `application-local.properties`. Там можешь указать url, username, password от своего локально запущенного Postgres

2023-06-28 15:57 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +        SqlParameterSource parametr = new MapSqlParameterSource("sName", inputRecord.getShortName()).addValue("url", inputRecord.getUrl());
привык просто к такой записи

2023-06-28 16:19 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +        return result.equals(shortName);
согласен, подправил

2023-06-28 16:19 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +                .replace("[", "").replace("]", ""));
изменил

2023-06-28 16:19 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +    NamedParameterJdbcTemplate jdbcTemplate;
добавил

2023-06-28 16:27 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +    }
подправил

2023-06-28 16:28 UTC, VlaPol commented on src/main/resources/db.migration/V1__initial_schema.sql
> +-- SELECT us.url, us.short_name
убрал, оставлял для тестов, понятно что на реальном проекте этого не будет

2023-06-28 16:29 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/entity/ConvertRecord.java
> +@NoArgsConstructor(force = true)
не нужен

2023-06-28 16:29 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/entity/ConvertRecord.java
> +@Data
исправил

2023-06-28 16:30 UTC, VlaPol commented on src/main/resources/db.migration/V1__initial_schema.sql
это должны были быть 2 деректории

2023-07-12 15:42 UTC, oleg-grigorijan requested changes

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/configure/BlackListConfig.java
> +@ConfigurationPropertiesScan
`@ConfigurationPropertiesScan` используют на `@Configuration` классе, чтобы автоматичски создавать `@ConfigurationProperties` бины без перечисления в `@EnableConfigurationProperties`

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/resources/db/migration/V1__initial_schema.sql
> +    url        VARCHAR not null
Желательно использовать единый code style. Если используем UPPER_CASE для ключевых слов, то желательно везде

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/resources/application_local.properties
С нижним подчёркиванием работает? Привык видеть `-` разделитель

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +    BlackListConfig conf;
private final

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +    @Transactional(rollbackFor = RuntimeException.class)
`rollbackFor` не нужен для unchecked исключений

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        }
Не самый хороший способ, но домашка не про это, так что не принципиально.
Но повторяется код. `UUID.randomUUID().toString().replace("-", "").substring(0, 6);` вынести бы хотя бы

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        URI url = new URI(inputUrl);
Есть `URI.create(String)`, который выбрасывает unchecked исключение, а не URISyntaxException

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        } catch (NullPointerException e) {
Плохая практика отлавливать NullPointerException. Его лучше избегать в принципе. Логика не должна строиться на отлавливании Exception'ов

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +                    }
Collection#contains. Если использовать Set, то это ещё и сложность алгоритма О(1) в лучшем случае

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +            if (url.getScheme().equals("http") || url.getScheme().equals("https")) {
```
Set<String> allowedSchemes = Set.of("http", "https");
...
allowedSchemes.contains(url.getScheme())
```
было бы читаемее и расширяемее. А вообще происил через properties сделать

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +    private boolean isCorrectUrl(String inputUrl) throws URISyntaxException {
Куча вложенности с кучей return-ов на разных уровнях – не очень читаемо

2023-07-12 15:42 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        }
getTotal().orElse(0)

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        }
```
return utUrlRepository.getTranslateRecord(shortName)
  .orElseThrow(() -> new RuntimeException("Что-то пошло не так"));
```

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        String sName = shortName.substring(shortName.lastIndexOf('/') + 1);
А зачем нам на уровне бизнес-логики в shortName URL-адрес, который привязывает нас к конкретной реализации контроллера? Было бы лучше принимать сразу идентификатор

2023-07-12 15:42 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        Optional<ConvertRecord> translateRecord = cutUrlRepository.getTranslateRecord(shortName);
А зачем проверка на exists, когда мы потом всё равно делаем select данных с возвратом optional?

2023-07-12 15:42 UTC, grigo-oleg commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        }
А с какой целью? Чем нам DataAccessException не угодил?

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        }
`cutUrlRepository.getTranslateRecord(shortName).orElseThrow()`
А вообще было бы лучше, чтобы addNewRecord вернул созданную модель данных

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/exceptions/AppException.java
Автоформатирование

2023-07-12 15:42 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +            return tmpList.get(0).equals(shortName);
А в каком случае это должно не выполниться?

2023-07-27 09:02 UTC, VlaPol commented on src/main/resources/db/migration/V1__initial_schema.sql
> +    url        VARCHAR not null
упустил

2023-07-27 09:03 UTC, VlaPol commented on src/main/resources/application_local.properties
да, на текущем проекте так таблицы называются, я на автомате и здесь так же написал

2023-07-27 09:04 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +    BlackListConfig conf;
да, косяк )

2023-07-27 09:09 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        }
подправил

2023-07-27 09:11 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        URI url = new URI(inputUrl);
исправил

2023-07-27 09:13 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        } catch (NullPointerException e) {
там по идее и не должно быть ее (я не придумал вариант), потому проверка на всякий случай

2023-07-27 09:19 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        }
), есть такое

2023-07-27 09:50 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        String sName = shortName.substring(shortName.lastIndexOf('/') + 1);
это моя бизнес-логика) я исходил из принятия ссылки

2023-07-27 09:53 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        Optional<ConvertRecord> translateRecord = cutUrlRepository.getTranslateRecord(shortName);
ну да, лишнее

2023-07-27 09:54 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        }
убрал

2023-07-27 10:06 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +            return tmpList.get(0).equals(shortName);
согласен, лішнее

2023-08-13 11:25 UTC, oleg-grigorijan approved these changes

2023-08-13 11:25 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/service/CutUrlServiceImpl.java
> +        }
А зачем нам тут всё подряд отлавливать? Причём в том числе `new AppException("Введен некоректный адрес или адрес находится в блокировке")`

2023-08-13 11:25 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/configure/BlackListConfig.java
> +public class BlackListConfig {
Более говорящее бы имя. Чёрный список чего?

2023-08-13 11:25 UTC, oleg-grigorijan commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +        return false;
`return !tmpList.isEmpty()`

2023-08-13 13:50 UTC, VlaPol commented on src/main/java/by/tms/url_cuter/repository/CutUrlRepositoryImpl.java
> +        return false;
или так )

2023-08-13 13:50 UTC, merged